### ISSUE TITLE
axum-csp incompatible http version of axum 0.7.x

### ISSUE THREAD

**Issue by johansmitsnl** [yaleman/goatns#416]
With axum `0.7.x` they switched to a newer version of http `1.0.0`. The `HeaderValue` are incompatible.

In #405 you try to update the http crate. By why don't you use the `http` from `axum::http`. This way you are always compatible with the axum version.

**Comment by yaleman** [comment]
I'll see if I can swap to using the axum http version. (#405 was an automated update)

**Comment by yaleman** [comment]
0.0.6 was released with the updates as suggested, I can't figure out how to update to axum 0.7.x today so I'll have to work that out soon.

**Comment by yaleman** [comment]
0.0.7's up.
